test 5

diff --git a/scripts/git/hooks/pre-commit b/scripts/git/hooks/pre-commit
--- a/scripts/git/hooks/pre-commit
+++ b/scripts/git/hooks/pre-commit
@@ -1,94 +1,35 @@
 #!/bin/zsh
 
+FILE="$1"
+
 echo "Pre-commit hook is running"
 
+# Check if the file has a .ipynb extension
+if [[ "$FILE" != *.ipynb ]]; then
+	echo "The file is not a Jupyter notebook (.ipynb). Skipping."
+	exit 0
+fi
+
+# Check if git is providing it with a file to check
 if [ -z "$1" ]; then
-    echo "Usage: $0 <notebook.ipynb>"
-    exit 1
+	echo "Usage: $0 <file>"
+	exit 1
 fi
 
+# Check if jq is installed
 if ! command -v jq > /dev/null 2>&1; then
-    echo "Error: jq is not installed."
-    exit 1
+	echo "Error: jq is not installed."
+	exit 2
 fi
 
-notebook="$1"
-echo "Processing notebook: $notebook"
-
-exit 2
-
-#
-# This script removes metadata and outputs from cells in a notebook.
-#
-# The following cells must remain empty to prevent leaking sensitive information:
-# - {"metadata": {}},
-# - {"outputs": []},
-# 
-# Jupyter notebooks are JSON files:
-# {
-#  "cells": [
-#     {
-#      "cell_type": "markdown",
-#      "metadata": {},
-#      "source": [
-#         "## This is a markdown cell"
-#      ]
-#     },
-#     {
-#      "cell_type": "code",
-#      "execution_count": null,
-#      "metadata": {},
-#      "outputs": [],
-#      "source": [
-#         "# This is a code cell\n",
-#         "print(\"Hello, world!\")"
-#      ]
-#     }
-#  ],
-#  "metadata": {
-#     "kernelspec": {
-#      "display_name": "Python 3",
-#      "language": "python",
-#      "name": "python3"
-#     },
-#     "language_info": {
-#      "codemirror_mode": {
-#         "name": "ipython",
-#         "version": 3
-#      },
-#      "file_extension": ".py",
-#      "mimetype": "text/x-python",
-#      "name": "python",
-#      "nbconvert_exporter": "python",
-#      "pygments_lexer": "ipython3",
-#      "version": "3.8.5"
-#     }
-#  },
-#  "nbformat": 4,
-#  "nbformat_minor": 4
-# }
-#
-#
-# Usage:
-#   $ ./strip-single-notebook.sh <notebook>
-if [ -z "$1" ]; then
-    echo "Usage: $0 <notebook.ipynb>"
-    exit 1
-fi
-
-if ! command -v jq > /dev/null 2>&1; then
-    echo "Error: jq is not installed."
-    exit 1
-fi
-
-notebook="$1"
+echo "Processing file: $FILE"
 
 jq '
-    .cells |= map(
-        if .cell_type == "code" then
-            .outputs = [] | .metadata = {} | .execution_count = null
-        else
-            .
-        end
-    )
-' "$notebook" > tmp.$$.ipynb && mv tmp.$$.ipynb "$notebook"
+	.cells |= map(
+		if .cell_type == "code" then
+			.outputs = [] | .metadata = {} | .execution_count = null
+		else
+			.
+		end
+	)
+' "$FILE" > tmp.$$.ipynb && mv tmp.$$.ipynb "$FILE"
