test pre-commit hook

diff --git a/scripts/git/hooks/pre-commit b/scripts/git/hooks/pre-commit
--- a/scripts/git/hooks/pre-commit
+++ b/scripts/git/hooks/pre-commit
@@ -1,49 +1,76 @@
-#!/bin/sh
+#!/bin/zsh
 #
-# An example hook script to verify what is about to be committed.
-# Called by "git commit" with no arguments.  The hook should
-# exit with non-zero status after issuing an appropriate message if
-# it wants to stop the commit.
+# This script removes metadata and outputs from cells in a notebook.
 #
-# To enable this hook, rename this file to "pre-commit".
-
-if git rev-parse --verify HEAD >/dev/null 2>&1
-then
-	against=HEAD
-else
-	# Initial commit: diff against an empty tree object
-	against=$(git hash-object -t tree /dev/null)
+# The following cells must remain empty to prevent leaking sensitive information:
+# - {"metadata": {}},
+# - {"outputs": []},
+# 
+# Jupyter notebooks are JSON files:
+# {
+#  "cells": [
+#     {
+#      "cell_type": "markdown",
+#      "metadata": {},
+#      "source": [
+#         "## This is a markdown cell"
+#      ]
+#     },
+#     {
+#      "cell_type": "code",
+#      "execution_count": null,
+#      "metadata": {},
+#      "outputs": [],
+#      "source": [
+#         "# This is a code cell\n",
+#         "print(\"Hello, world!\")"
+#      ]
+#     }
+#  ],
+#  "metadata": {
+#     "kernelspec": {
+#      "display_name": "Python 3",
+#      "language": "python",
+#      "name": "python3"
+#     },
+#     "language_info": {
+#      "codemirror_mode": {
+#         "name": "ipython",
+#         "version": 3
+#      },
+#      "file_extension": ".py",
+#      "mimetype": "text/x-python",
+#      "name": "python",
+#      "nbconvert_exporter": "python",
+#      "pygments_lexer": "ipython3",
+#      "version": "3.8.5"
+#     }
+#  },
+#  "nbformat": 4,
+#  "nbformat_minor": 4
+# }
+#
+#
+# Usage:
+#   $ ./strip-single-notebook.sh <notebook>
+if [ -z "$1" ]; then
+    echo "Usage: $0 <notebook.ipynb>"
+    exit 1
 fi
 
-# If you want to allow non-ASCII filenames set this variable to true.
-allownonascii=$(git config --type=bool hooks.allownonascii)
-
-# Redirect output to stderr.
-exec 1>&2
-
-# Cross platform projects tend to avoid non-ASCII filenames; prevent
-# them from being added to the repository. We exploit the fact that the
-# printable range starts at the space character and ends with tilde.
-if [ "$allownonascii" != "true" ] &&
-	# Note that the use of brackets around a tr range is ok here, (it's
-	# even required, for portability to Solaris 10's /usr/bin/tr), since
-	# the square bracket bytes happen to fall in the designated range.
-	test $(git diff --cached --name-only --diff-filter=A -z $against |
-	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
-then
-	cat <<\EOF
-Error: Attempt to add a non-ASCII file name.
-
-This can cause problems if you want to work with people on other platforms.
-
-To be portable it is advisable to rename the file.
-
-If you know what you are doing you can disable this check using:
-
-  git config hooks.allownonascii true
-EOF
-	exit 1
+if ! command -v jq > /dev/null 2>&1; then
+    echo "Error: jq is not installed."
+    exit 1
 fi
 
-# If there are whitespace errors, print the offending file names and fail.
-exec git diff-index --check --cached $against --
+notebook="$1"
+
+jq '
+    .cells |= map(
+        if .cell_type == "code" then
+            .outputs = [] | .metadata = {} | .execution_count = null
+        else
+            .
+        end
+    )
+' "$notebook" > tmp.$$.ipynb && mv tmp.$$.ipynb "$notebook"
